language: node_js

notifications:
  email: false

before_install:
  - npm install ansi-codes@0.0.0 new-format@0.0.0
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"
    # Workaround for Selenium #3280 issue
  - "sudo sed -i 's/^127\\.0\\.0\\.1.*$/127.0.0.1 localhost/' /etc/hosts"
script: "npm run $TASK"

matrix:
  fast_finish: true
  include:
  - node_js: 4
    env: TASK=test
  - node_js: 5
    env: TASK=test
  - node_js: 6
    env: TASK=test
  - node_js: 7
    env: TASK=test
  - node_js: 6
    env: TASK=test-browser
